### ISSUE TITLE
curl not found?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [fgrehm/vocker#15]
I'd love if you guys could supply a Vagrantfile example that works without modification. The examples seem to use placeholders like "your-box" or are incomplete in some way.
## I'm using the following Vagrantfile:

Vagrant.configure("2") do |config|
  config.vm.box = 'raring64'
  config.vm.provision :docker do |docker|
    docker.pull_images 'ubuntu', 'busybox'
    docker.run 'echo ls -la --color', 'ubuntu'
  end
## end

And I get:
bash: line 2: curl: command not found
gpg: no valid OpenPGP data found.

I don't think curl comes standard on ubuntu boxes, and I've never used multiple provisioning steps; I guess I should add a "sudo apt-get install -y curl" step, but is it OK to have both shell-script provisioning and Vocker? Isn't this something Vocker should do if it needs curl?

**Comment by fgrehm** [comment]
Thanks for reporting, I'll push a patch for auto curl installation later on tonight. But in the meantime, you can do something like:

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = 'raring64'
  config.vm.provision :shell, inline: 'apt-get install -y curl'
  config.vm.provision :docker do |docker|
    docker.pull_images 'ubuntu', 'busybox'
    docker.run 'echo ls -la --color', 'ubuntu'
  end
end
```

**Comment by fgrehm** [comment]
Done! New release coming out _soonish_

**Comment by GeoffreyPlitt** [comment]
Awesome!

On Thu, Nov 7, 2013 at 3:39 PM, Fabio Rehm notifications@github.com wrote:

> Done! New release coming out _soonish_
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fgrehm/vocker/issues/15#issuecomment-28018302
> .

## 

http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915
