### ISSUE TITLE
vocker is not provisioning docker in vagrant box

### ISSUE THREAD

**Issue by Aamir010** [fgrehm/vocker#21]
--- Provision code in vagrant file ---
config.vm.provision "docker" do |a|
    a.pull_images 'ubuntu'
end

--- Error Trace ----
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisio                                                                                                                                  ners/docker/cap/redhat/docker_install.rb:6:in `docker_install': wrong number of                                                                                                                                   arguments (2 for 1) (ArgumentError)
        from C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib                                                                                                                                  /vagrant/capability_host.rb:111:in`call'
        from C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib                                                                                                                                  /vagrant/capability_host.rb:111:in `capability'

**Comment by fgrehm** [comment]
Sorry but as noted on the readme this plugin is no longer being maintained as its functionality has been merged back into Vagrant core. Please [read up the docker provisioner docs](https://www.vagrantup.com/docs/provisioning/docker.html) and if that doesn't help feel free to reach out for help on the mailing list or vagrant's issue tracker :beers:
